<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="urdad"
    nsURI="http://www.urdad.org/2010/urdad" nsPrefix="urdad">
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="author" value="fritz@solms.co.za"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="documentation" value="This is a ecore encoding of the URDAD meta-model. URDAD is a services-oriented&#xA;&#x9; analysis and design methodology which is meant for technology neutral analysis&#xA;&#x9; and design resulting in a PIM (platform-independent model) which can be used &#xA;&#x9; in the context of model-driven development (e.g. MDA)."/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Componentize meta-model"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="How to support componentized models?"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Should primitives be sourced from OCL?"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Should awaiting on signals be supported and if so, how?"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Persistence &amp; CRUD methods via entity manager. Problem: these are in model, not meta-model domain"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Basic data types"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Exception message construction perhaps via OCL to include context info"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="todo" value="Fully qualified names support in XText (it is in ECore, but not in default XText mapping - can be done in XText)"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibilityDomains"
        upperBound="-1" eType="#//ResponsibilityDomain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponsibilityDomain" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalConstraints"
        upperBound="-1" eType="#//FunctionalConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityRequirements" upperBound="-1"
        eType="#//QualityRequirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionString" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefinedConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityConstraint" abstract="true"
      eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeMultiplicityConstraint" eSuperTypes="#//MultiplicityConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minOccurs" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurs" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicDataType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//DataStructure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exception" eSuperTypes="#//DataStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//BasicDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedType" lowerBound="1"
        eType="#//DataStructure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicityConstraint"
        eType="#//MultiplicityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Aggregation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" lowerBound="1"
        upperBound="-1" eType="#//ResponsibilityDomain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityRequirement" eSuperTypes="#//Requirement">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="documentation" value="A quality requirement is a non-functional requirement around quality of service. &#xA;&#x9;&#x9;Typical examples of quality requirements include scalability, reliability, performance, security and auditability."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementExpression"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalConstraint" abstract="true"
      eSuperTypes="#//DefinedConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement" eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalConstraint" lowerBound="1"
        eType="#//FunctionalConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreCondition" eSuperTypes="#//FunctionalConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" lowerBound="1"
        eType="#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostCondition" eSuperTypes="#//FunctionalConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverseService" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requestClassNameEqualsServiceNamePlusRequest resultClassNameEqualsServiceNamePlusResult"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="documentation" value="A requirement for a service."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="documentation" value="Pre and post-conditions composed in service because constraint definitions are context specific"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requestClassNameEqualsServiceNamePlusRequest" value="&#xA;&#x9;&#x9;  (self.request.name.substring(self.request.name.size()-6,self.request.name.size()) = 'Request')&#xA;&#x9;&#x9;  and&#xA;&#x9;&#x9;  (self.request.name.substring(1,self.name.size()) = self.name.substring(1,1).toUpper().concat&#xA;&#x9;&#x9;  (self.name.substring(2,self.name.size())))"/>
      <details key="resultClassNameEqualsServiceNamePlusResult" value="&#xA;&#x9;&#x9;  (self.request.name.substring(self.request.name.size()-5,self.request.name.size()) = 'Result')&#xA;&#x9;&#x9;  and&#xA;&#x9;&#x9;  (self.request.name.substring(1,self.name.size()) = self.name.substring(1,1).toUpper().concat&#xA;&#x9;&#x9;  (self.name.substring(2,self.name.size())))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" lowerBound="1"
        eType="#//DataStructure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//DataStructure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirements"
        lowerBound="1" upperBound="-1" eType="#//FunctionalRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityRequirements" upperBound="-1"
        eType="#//QualityRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processActivity" lowerBound="1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeActivity" abstract="true" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivitySequence" eSuperTypes="#//CompositeActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcurrentActivities" eSuperTypes="#//CompositeActivity">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="documentation" value="A collection of activities which are independent of one another and which can be performed concurrently. The end of this element implies a synchronization bar which blocks the process until all non-BackgroundThreads have been completed."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalActivities"
        upperBound="-1" eType="#//ConditionalActivity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//ConditionalActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRequestActivity" abstract="true"
      eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestContraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreConditionActivity" eSuperTypes="#//ServiceRequestActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" lowerBound="1"
        eType="#//PreCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionContraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostConditionActivity" eSuperTypes="#//ServiceRequestActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" lowerBound="1"
        eType="#//PostCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverseRequestContraints"
        upperBound="-1" eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrePostConditionActivity" eSuperTypes="#//PreConditionActivity #//PostConditionActivity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="preAndPostConditionAddressedThroughSameService"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="preAndPostConditionAddressedThroughSameService" value="&#xA;&#x9;&#x9;&#x9;preCondition.requiredService = postCondition.requiredService"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnResultActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultContraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
